const usernames = [
  'northeastwither',
  'guiltlessforsaken',
  'physicistmoo',
  'lardresort',
  'expressionunthinking',
  'bellowingscientist',
  'submitcot',
  'dearsport',
  'godchamber',
  'typicallysquad',
  'lumbarrotten',
  'doyltfor',
  'writheliar',
  'trustconscious',
  'couplekisseasily',
  'moanignore',
  'differenceden',
  'kindmake',
  'cynicalirate',
  'ailfluke',
  'pleasestoic',
  'applepantheon',
  'ensureloathsome',
  'tirenight',
  'escutcheonimage',
  'dapperthirty',
  'millionnine',
  'porschefeast',
  'mooshroompetite',
  'engagevenison',
  'depressedpriest',
  'sitcross',
  'metallicnumber',
  'zonesomewhere',
  'reasonableangry',
  'yoursphilosophy',
  'lingerietipped',
  'seagullagonizing',
  'wigcollected',
  'trusteeflapjack',
  'problemspinnaker',
  'foregoingwritable',
  'hardtofindchildren',
  'piccalilliarena',
  'wonderlandunless',
  'slipglove',
  'quiverlearned',
  'esteemedshore',
  'fewerold',
  'criticismoil',
  'pagespirited',
  'americanenderman',
  'irritatesausage',
  'publisherhorizon',
  'coralodds',
  'kalefitzroy',
  'raidfalse',
  'consumersacred',
  'restdeltoid',
  'statisticsmotor',
  'prettyingclifden',
  'obsceneworkshop',
  'passelminibus',
  'muttondashing',
  'othersformula',
  'birthsupreme',
  'netherscorpion',
  'areweatherly',
  'bagelfour',
  'backingartiste',
  'drowninvolve',
  'bikinghall',
  'alterhowl',
  'goldmedalcandid',
  'sunpretzel',
  'pingpassel',
  'savoryshipton',
  'swanmemory',
  'wastesglean',
  'gingerexercise',
  'throughsweat'
];

const emails = [
  'okeefe.concepcion@hotmail.com',
  'richie01@grimes.net',
  'aharris@gmail.com',
  'apouros@gmail.com',
  'anderson.brando@gmail.com',
  'alice.dooley@walsh.com',
  'margarita.ruecker@hotmail.com',
  'kassandra.kiehn@runte.com',
  'robb87@yahoo.com',
  'boyer.ashley@mann.com',
  'hammes.carlo@yahoo.com',
  'liza28@gmail.com',
  'dward@gmail.com',
  'pattie95@stiedemann.com',
  'uhackett@mayer.biz',
  'quentin.heathcote@lemke.com',
  'oconner.enoch@hotmail.com',
  'slarson@yahoo.com',
  'iankunding@gmail.com',
  'asauer@rath.com',
  'aubrey82@rogahn.com',
  'pleannon@doyle.net',
  'ydickens@yahoo.com',
  'dedric.collins@yahoo.com',
  'heloise59@adams.org',
  'ben94@mckenzie.com',
  'mary.keeling@yahoo.com',
  'vpagac@gmail.com',
  'astreich@yahoo.com',
  'kellie.waelchi@hotmail.com',
  'jedidiah26@reynolds.net',
  'ahmad.beatty@gmail.com',
  'jasen69@yahoo.com',
  'denesik.stephanie@bernier.com',
  'wehner.dangelo@hotmail.com',
  'megane36@roob.com',
  'medhurst.vicenta@hotmail.com',
  'gleason.nona@ruecker.com',
  'vabernathy@gmail.com',
  'gleichner.myriam@hotmail.com',
  'nhauck@lowe.com',
  'enoch25@stamm.org',
  'micaela80@skiles.com',
  'gkessler@gmail.com',
  'jaime.lang@hotmail.com',
  'rohan.charles@cummings.com',
  'lucious95@hotmail.com',
  'skerluke@auer.com',
  'edmund.bauch@hotmail.com',
  'stanford64@hotmail.com',
  'annamae.larson@hotmail.com',
  'jazmin.thiel@yahoo.com',
  'marion76@greenholt.org',
  'della65@hotmail.com',
  'joanie86@gmail.com',
  'margarete.schaefer@gmail.com',
  'watsica.jamie@gmail.com',
  'lexie52@mcglynn.com',
  'xwillms@lynch.info',
  'avolkman@yahoo.com',
  'lemuel22@mccullough.biz',
  'prosacco.maryam@hotmail.com',
  'maggie05@feest.org',
  'ronaldo21@gmail.com',
  'myra.harber@hotmail.com',
  'lilla98@gmail.com',
  'walton.heathcote@cartwright.com',
  'murazik.rogers@mraz.net',
  'nbruen@wyman.com',
  'narciso80@gmail.com',
  'xchamplin@satterfield.com',
  'eruecker@hotmail.com',
  'oconner.wade@hotmail.com',
  'maximillia60@yahoo.com',
  'schaefer.gene@hotmail.com',
  'joshua.weber@yahoo.com',
  'fspinka@hotmail.com',
  'minnie.leffler@moore.com',
  'amelie20@yahoo.com',
  'darren70@vandervort.net',
  'werner.rau@hills.com',
];

const texts = [
  'Pasture he invited mr company shyness.',
  'But when shot real her.',
  'Chamber her observe visited removal six sending himself boy.',
  'At exquisite existence if an oh dependent excellent.',
  'Are gay head need down draw. Misery wonder enable mutual get set oppose the uneasy.',
  'End why melancholy estimating her had indulgence middletons.',
  'Say ferrars demands besides her address.',
  'Blind going you merit few fancy their.',
  'Of resolve to gravity thought my prepare chamber so.',
  'Unsatiable entreaties collecting may sympathize nay interested instrument.',
  'If continue building numerous of at relation in margaret.',
  'Lasted engage roused mother an am at.',
  'Other early while if by do to.',
  'Missed living excuse as be.',
  'Cause heard fat above first shall for.',
  'My smiling to he removal weather on anxious.',
  'Ignorant branched humanity led now marianne too strongly entrance.',
  'Rose to shew bore no ye of paid rent form.',
  'Old design are dinner better nearer silent excuse.',
  'She which are maids boy sense her shade.',
  'Considered reasonable we affronting on expression in.',
  'So cordial anxious mr delight.',
  'Shot his has must wish from sell nay.',
  'Remark fat set why are sudden depend change entire wanted.',
  'Performed remainder attending led fat residence far.',
  'Perhaps far exposed age effects.',
  'Now distrusts you her delivered applauded affection out sincerity.',
  'As tolerably recommend shameless unfeeling he objection consisted.',
  'She although cheerful perceive screened throwing met not eat distance.',
  'Viewing hastily or written dearest elderly up weather it as.',
  'So direction so sweetness or extremity at daughters.',
  'Provided put unpacked now but bringing.',
  'By spite about do of do allow blush.',
  'Additions in conveying or collected objection in.',
  'Suffer few desire wonder her object hardly nearer.',
  'Abroad no chatty others my silent an.',
  'Fat way appear denote who wholly narrow gay settle.',
  'Companions fat add insensible everything and friendship conviction themselves.',
  'Theirs months ten had add narrow own.',
  'She who arrival end how fertile enabled.',
  'Brother she add yet see minuter natural smiling article painted.',
  'Themselves at dispatched interested insensible am be prosperous reasonably it.',
  'In either so spring wished.',
  'Melancholy way she boisterous use friendship she dissimilar considered expression.',
  'Sex quick arose mrs lived.',
  'Mr things do plenty others an vanity myself waited to.',
  'Always parish tastes at as mr father dining at.',
  'Affronting everything discretion men now own did.',
  'Still round match we to.',
  'Frankness pronounce daughters remainder extensive has but.',
  'Happiness cordially one determine concluded fat.',
  'Plenty season beyond by hardly giving of.',
  'Consulted or acuteness dejection an smallness if.',
  'Outward general passage another as it.',
  'Very his are come man walk one next.',
  'Delighted prevailed supported too not remainder perpetual who furnished.',
  'Nay affronting bed projection compliment instrument.',
  'Woody equal ask saw sir weeks aware decay.',
  'Entrance prospect removing we packages strictly is no smallest he.',
  'For hopes may chief get hours day rooms.',
  'Oh no turned behind polite piqued enough at.',
  'Forbade few through inquiry blushes you.',
  'Cousin no itself eldest it in dinner latter missed no.',
  'Boisterous estimating interested collecting get conviction friendship say boy.',
  'Him mrs shy article smiling respect opinion excited.',
  'Welcomed humoured rejoiced peculiar to in an.',
  'Its sometimes her behaviour are contented.',
  'Do listening am eagerness oh objection collected.',
  'Together gay feelings continue juvenile had off one.',
  'Unknown may service subject her letters one bed.',
  'Child years noise ye in forty. Loud in this in both hold.',
  'My entrance me is disposal bachelor remember relation.',
  'Am no an listening depending up believing.',
  'Enough around remove to barton agreed regret in or it.',
  'Advantage mr estimable be commanded provision.',
  'Year well shot deny shew come now had.',
  'Shall downs stand marry taken his for out.',
  'Do related mr account brandon an up.',
  'Wrong for never ready ham these witty him.',
  'Our compass see age uncivil matters weather forbade her minutes.',
  'Ready how but truth son new under.'
]

// Export the functions for use in seed.js
module.exports = { usernames, emails, texts };
